language: node_js
node_js:
  - "10"
cache: npm

install:
  - npm install -g gitbook-cli
  - gitbook install

script:
  - gitbook build

after_script:
  - git checkout -b gh-pages
  - shopt -s extglob
  - rm -fr !(_book)
  - mv -f _book/* ../notes
  - git add .
  - git commit -m "Updated By Travis-CI With Build $(basename $TRAVIS_REPO_SLUG):$TRAVIS_BUILD_NUMBER For Github Pages"
  - git push --force --quiet "https://${GITHUB_TOKEN}@${REF}"

branches:
  only:
    - master

env:
  global:
    - REF=github.com/dyingtime/notes.git # 设置 github 地址
